AWSTemplateFormatVersion: 2010-09-09

Parameters:
  AuditAWSAccountEmail:
    Type: String
  LogArchiveAWSAccountEmail:
    Type: String

Resources:

  SetupControlTowerCanaryRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/AdministratorAccess # fixme: least privilege
      Policies:
        - PolicyName: AllowS3List
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:ListAllMyBuckets
                  - s3:GetBucketLocation
                  - cloudwatch:PutMetricData
                Resource: '*'

  SetupControlTowerCanary:
    Type: AWS::Synthetics::Canary
    Properties:
      Name: fnptcm-bootstrap-ct
      ArtifactS3Location: !Sub s3://${SetupControlTowerArtifactLocation}
      ExecutionRoleArn: !GetAtt SetupControlTowerCanaryRole.Arn
      RuntimeVersion: syn-1.0
      StartCanaryAfterCreation: true
      RunConfig:
        TimeoutInSeconds: 600
      Schedule:
        DurationInSeconds: 3600
        Expression: rate(0 minute)
      Code:
        Handler: pageLoadBlueprint.handler
        Script: !Sub |
          var synthetics = require('Synthetics');
          const log = require('SyntheticsLogger');

          const httpGet = url => {
            const https = require('https');
            return new Promise((resolve, reject) => {
              https.get(url, res => {
                res.setEncoding('utf8');
                let body = '';
                res.on('data', chunk => body += chunk);
                res.on('end', () => resolve(body));
              }).on('error', reject);
            });
          };

          const flowBuilderBlueprint = async function () {
            let page = await synthetics.getPage();

            await synthetics.executeStep('consoleLogin', async function () {
              const AWS = require("aws-sdk");

              const federationEndpoint = 'https://signin.aws.amazon.com/federation';
              const issuer = 'founopticum';
              const destination = 'https://console.aws.amazon.com/';

              let credentials = await AWS.config.credentialProvider.resolve((err, cred) => { return cred; }).resolvePromise()

              const session = {
                sessionId: credentials.accessKeyId,
                sessionKey: credentials.secretAccessKey,
                sessionToken: credentials.sessionToken
              };

              const encodedSession = encodeURIComponent(JSON.stringify(session));
              const signinTokenUrl = `${!federationEndpoint}?Action=getSigninToken&SessionDuration=3600&Session=${!encodedSession}`;

              const signinResponse = await httpGet(signinTokenUrl);

              let consoleLoginUrl = `${!federationEndpoint}?Action=login&Issuer=${!issuer}&Destination=${!destination}&SigninToken=${!
                JSON.parse(signinResponse).SigninToken
              }`;

              await page.goto(consoleLoginUrl, {waitUntil: ['load', 'networkidle0']});

            });

            await synthetics.executeStep('gotoCT', async function () {
              await page.goto("https://eu-west-1.console.aws.amazon.com/controltower/home?region=eu-west-1", {waitUntil: ['load', 'networkidle0']});
            });

            await synthetics.executeStep('gotoLlandingZoneCreation', async function () {
              await page.click("#get-started-btn > button");
              await page.waitFor(10000); // waitForNavigation does not work here, so use sleep()
            });

            await synthetics.executeStep('createLandingZone', async function () {
              await page.click("#awsui-input-0")
              await page.click("#awsui-input-1")
              await page.click("#awsui-input-2")
              await page.type("#awsui-input-0", "${LogArchiveAWSAccountEmail}")
              await page.type("#awsui-input-1", "${AuditAWSAccountEmail}")
              await page.click("#awsui-checkbox-0")
              await page.waitFor(10000); // wait for AWS UI to settle, then click
              await page.click("#save-button > button");
              await page.waitForNavigation({waitUntil: ['domcontentloaded']});
            });

          };

          exports.handler = async () => {
            return await flowBuilderBlueprint();
          };

  SetupControlTowerArtifactLocation:
    Type: AWS::S3::Bucket

  SetupControlTowerArtifactLocationPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref SetupControlTowerArtifactLocation
      PolicyDocument:
        Statement:
          - Effect: Allow
            Action: '*'
            Resource:
              - !GetAtt SetupControlTowerArtifactLocation.Arn
              - !Sub ${SetupControlTowerArtifactLocation.Arn}/*
            Principal:
              AWS: !GetAtt SetupControlTowerCanaryRole.Arn

#  SetupLandingZoneRule:
#    Type: AWS::Events::Rule
#    Properties:
#      EventPattern:
#        detail-type:
#          - AWS Service Event via CloudTrail
#        source:
#          - aws.controltower
#        detail:
#          serviceEventDetails:
#            setupLandingZoneStatus:
#              state:
#                - SUCCEEDED
#          eventName:
#            - SetupLandingZone
#
#      State: ENABLED
#      Targets:
#        - Arn: !Sub arn:${AWS::Partition}:ssm:${AWS::Region}:${AWS::AccountId}:automation-definition/${FounopticumBootstrap}
#          Id: SetupLandingZone
#          RoleArn: !GetAtt SSMAutomationExecutionRoleforCWEvents.Arn
#          InputTransformer:
#            InputPathsMap:
#              organizationalUnits: $.detail.serviceEventDetails.setupLandingZoneStatus.organizationalUnits
#              accounts: $.detail.serviceEventDetails.setupLandingZoneStatus.accounts
#            InputTemplate: |
#              {
#                "organizationalUnits": [<organizationalUnits>],
#                "accounts": [<accounts>]
#              }

  UpdateLandingZoneRule:
    Type: AWS::Events::Rule
    Properties:
      EventPattern:
#        detail-type:
#          - AWS Service Event via CloudTrail
        source:
          - schnuffer
#        detail:
#          serviceEventDetails:
#            updateLandingZoneStatus:
#              state:
#                - SUCCEEDED
#          eventName:
#            - UpdateLandingZone

      State: ENABLED
      Targets:
        - Arn: !Sub arn:${AWS::Partition}:ssm:${AWS::Region}:${AWS::AccountId}:automation-definition/${FounopticumBootstrap}
          Id: UpdateLandingZone
          RoleArn: !GetAtt SSMAutomationExecutionRoleforCWEvents.Arn
          InputTransformer:
            # currently, it seems that only passing strings to SSM Automation is allowed
            InputPathsMap:
              organizationalUnit0Id: $.detail.serviceEventDetails.updateLandingZoneStatus.organizationalUnits[0].organizationalUnitId
              organizationalUnit1Id: $.detail.serviceEventDetails.updateLandingZoneStatus.organizationalUnits[1].organizationalUnitId
              organizationalUnit1Name: $.detail.serviceEventDetails.updateLandingZoneStatus.organizationalUnits[1].organizationalUnitName
              organizationalUnit0Name: $.detail.serviceEventDetails.updateLandingZoneStatus.organizationalUnits[0].organizationalUnitName
              accounts0Id: $.detail.serviceEventDetails.updateLandingZoneStatus.accounts[0].accountId
              accounts0Name: $.detail.serviceEventDetails.updateLandingZoneStatus.accounts[0].accountName
              accounts1Id: $.detail.serviceEventDetails.updateLandingZoneStatus.accounts[1].accountId
              accounts1Name: $.detail.serviceEventDetails.updateLandingZoneStatus.accounts[1].accountName
              accounts2Id: $.detail.serviceEventDetails.updateLandingZoneStatus.accounts[2].accountId
              accounts2Name: $.detail.serviceEventDetails.updateLandingZoneStatus.accounts
            InputTemplate: |
              {
                "organizationalUnit0Id": [<organizationalUnit0Id>],
                "organizationalUnit1Id": [<organizationalUnit1Id>],
                "organizationalUnit1Name": [<organizationalUnit1Name>],
                "organizationalUnit0Name": [<organizationalUnit0Name>],
                "accounts0Id": [<accounts0Id>],
                "accounts0Name": [<accounts0Name>],
                "accounts1Id": [<accounts1Id>],
                "accounts1Name": [<accounts1Name>],
                "accounts2Id": [<accounts2Id>],
                "accounts2Name": [<accounts2Name>]
              }

  SSMAutomationExecutionRoleforCWEvents:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: events.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: AllowStartAutomationExecution
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - ssm:StartAutomationExecution
                Resource: !Sub arn:${AWS::Partition}:ssm:${AWS::Region}:${AWS::AccountId}:automation-definition/${FounopticumBootstrap}:*

  FounopticumBootstrap:
    Type: AWS::SSM::Document
    Properties:
      DocumentType: Automation
      Content:
        schemaVersion: '0.3'
        assumeRole: !GetAtt StartExecutionRoleForSSM.Arn
        parameters:
          organizationalUnit0Id:
            type: String
          organizationalUnit1Id:
            type: String
          organizationalUnit0Name:
            type: String
          organizationalUnit1Name:
            type: String
          accounts0Id:
            type: String
          accounts0Name:
            type: String
          accounts1Id:
            type: String
          accounts1Name:
            type: String
          accounts2Id:
            type: String
          accounts2Name:
            type: StringMap
        mainSteps:
          - name: StartAutomationExecution
            action: aws:executeScript
            inputs:
              Runtime: python3.7
              Handler: handler
              InputPayload:
                organizationalUnit0Id: '{{ organizationalUnit0Id }}'
                organizationalUnit1Id: '{{ organizationalUnit1Id }}'
                organizationalUnit0Name: '{{ organizationalUnit0Name }}'
                organizationalUnit1Name: '{{ organizationalUnit1Name }}'
                accounts0Id: '{{ accounts0Id }}'
                accounts0Name: '{{ accounts0Name }}'
                accounts1Id: '{{ accounts1Id }}'
                accounts1Name: '{{ accounts1Name }}'
                accounts2Id: '{{ accounts2Id }}'
                accounts2Name: '{{ accounts2Name }}'
                  
                
              Script: |-
                def handler(events, context):
                    print(events)

  StartExecutionRoleForSSM:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: ssm.amazonaws.com
            Action: sts:AssumeRole
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSOrganizationsReadOnlyAccess
