AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Parameters:
  AuditAWSAccountEmail:
    Type: String
  LogArchiveAWSAccountEmail:
    Type: String
  Domain:
    Type: String
  TemplateUrlPrefix:
    Type: String

Resources:

  ControlTower:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub ${TemplateUrlPrefix}/components/00-control-tower.yaml
      Parameters:
        AuditAWSAccountEmail: !Ref AuditAWSAccountEmail
        LogArchiveAWSAccountEmail: !Ref LogArchiveAWSAccountEmail

  RootMail:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub ${TemplateUrlPrefix}/components/xx-rootmail.yaml
      Parameters:
        Domain: !Ref Domain

  GuardDuty:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub ${TemplateUrlPrefix}/components/01-guardduty.yaml

  SecurityHub:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub ${TemplateUrlPrefix}/components/04-security-hub.yaml

  ServiceControlPolicies:
    Type: AWS::CloudFormation::Stack
    DependsOn: ControlTower
    Properties:
      TemplateURL: !Sub ${TemplateUrlPrefix}/components/service-control-policies.yaml

Outputs:

  RootMailDelegationTarget:
    Description: Nameservers for the hosted zone delegation
    Value: !GetAtt RootMail.Outputs.NameServers
