AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Parameters:
  AuditAWSAccountEmail:
    Type: String
  LogArchiveAWSAccountEmail:
    Type: String
  Domain:
    Type: String
  IncludeControlTower:
    AllowedValues:
      - true
      - false
    Default: true
    Type: String
  IncludeGuardDuty:
    AllowedValues:
      - true
      - false
    Default: true
    Type: String
  IncludeSecurityHub:
    AllowedValues:
      - true
      - false
    Default: true
    Type: String
  IncludeServiceControlPolicies:
    AllowedValues:
      - true
      - false
    Default: true
    Type: String
  IncludeRootMail:
    AllowedValues:
      - true
      - false
    Default: true
    Type: String
  TemplateUrlPrefix:
    Type: String

Conditions:
  IncludeControlTower: !Equals [ !Ref IncludeControlTower, true ]
  IncludeGuardDuty: !And
    - !Condition IncludeControlTower
    - !Equals [ !Ref IncludeGuardDuty, true ]
  IncludeRootMail: !Equals [ !Ref IncludeRootMail, true ]
  IncludeSecurityHub: !And
    - !Condition IncludeControlTower
    - !Equals [ !Ref IncludeSecurityHub, true ]
  IncludeServiceControlPolicies: !And
    - !Condition IncludeControlTower
    - !Equals [ !Ref IncludeServiceControlPolicies, true ]

Resources:

  ControlTower:
    Condition: IncludeControlTower
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub ${TemplateUrlPrefix}/components/control-tower.yaml
      Parameters:
        AuditAWSAccountEmail: !Ref AuditAWSAccountEmail
        LogArchiveAWSAccountEmail: !Ref LogArchiveAWSAccountEmail

  GuardDuty:
    Condition: IncludeGuardDuty
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub ${TemplateUrlPrefix}/components/guardduty.yaml

  RootMail:
    Condition: IncludeRootMail
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub ${TemplateUrlPrefix}/components/rootmail.yaml
      Parameters:
        Domain: !Ref Domain

  SecurityHub:
    Condition: IncludeSecurityHub
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub ${TemplateUrlPrefix}/components/security-hub.yaml

  ServiceControlPolicies:
    Condition: IncludeServiceControlPolicies
    Type: AWS::CloudFormation::Stack
    DependsOn: ControlTower
    Properties:
      TemplateURL: !Sub ${TemplateUrlPrefix}/components/service-control-policies.yaml

Outputs:

  RootMailDelegationTarget:
    Description: Nameservers for the hosted zone delegation
    Value: !GetAtt RootMail.Outputs.DelegationTarget
