
name: Branch Deployments

on:
  push:
    branches: ['*']

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:


    - name: Checkout
      uses: actions/checkout@v2

    - name: Branch name
      run: echo running on branch ${GITHUB_REF##*/}
