
name: Release

on:
  push:
    branches: ['*', '!main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Example
      run: echo "ref is ${{ github.ref }}"
